name: apideploy

on : push

jobs:
  output:
    name: writeoutput
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Write output
        shell: pwsh
        run: |
          write-output 'test output line'